In [137]:
import pandas as pd

In [138]:
body = pd.read_excel("/home/mglee/VSCODE/git/ISDS/region/body0118.xlsx")
id = pd.read_excel("/home/mglee/VSCODE/git/ISDS/region/id.xlsx")

In [139]:
body[10:60]

,Unnamed: 0,dist,type,보건_영역평균,복지_영역평균,교육_영역평균,문화_영역평균,순위:보건,순위:복지,순위:교육,...,교육2 표준화값,교육3 표준화값,교육4 표준화값,교육5 표준화값,문화1 표준화값,문화2 표준화값,문화3 표준화값,문화4 표준화값,문화5 표준화값,문화6 표준화값
10,NaN,서울_중구,시군구,6.897709,5.365084,6.409564,6.263367,17,191.0,62,...,5.877146,7.252541,6.206017,NaN,NaN,NaN,6.911931,NaN,NaN,5.614803
11,NaN,용산구,시군구,6.631592,5.127551,5.803642,5.786113,33,211.0,147,...,5.863364,6.388396,6.194286,NaN,NaN,NaN,5.688156,NaN,NaN,5.884070
12,NaN,성동구,시군구,5.984506,5.271905,5.962873,5.359073,115,202.0,129,...,5.925431,6.929674,6.119206,NaN,NaN,NaN,5.359073,NaN,NaN,NaN
13,NaN,광진구,시군구,6.325881,5.152073,6.584678,5.143113,67,209.0,32,...,5.978680,7.831802,6.959159,NaN,NaN,NaN,5.143113,NaN,NaN,NaN
14,NaN,동대문구,시군구,6.608022,5.414188,6.649697,5.136839,35,185.0,26,...,5.847716,8.335096,6.621301,NaN,NaN,NaN,5.204816,NaN,NaN,5.068862
15,NaN,중랑구,시군구,5.644073,5.330522,5.987926,5.029991,169,194.0,124,...,5.933798,6.426381,6.313944,NaN,NaN,NaN,5.029991,NaN,NaN,NaN
16,NaN,성북구,시군구,5.632359,5.277801,6.686061,5.410492,171,199.0,21,...,5.992115,7.895901,6.736267,NaN,NaN,NaN,5.410492,NaN,NaN,NaN
17,NaN,강북구,시군구,5.715546,5.237576,9.021673,5.266519,157,203.0,1,...,19.167505,5.991934,6.701073,NaN,NaN,NaN,5.266519,NaN,NaN,NaN
18,NaN,도봉구,시군구,5.581343,5.702790,5.938474,5.215099,181,164.0,132,...,5.785049,6.257825,6.450026,NaN,NaN,NaN,5.215099,NaN,NaN,NaN
19,NaN,노원구,시군구,6.950992,5.855179,6.617947,5.963732,13,139.0,28,...,5.805374,7.162328,6.611916,NaN,NaN,NaN,5.245951,NaN,NaN,6.681514
20,NaN,은평구,시군구,5.855559,5.125537,5.914689,5.215099,134,212.0,137,...,5.662392,6.003804,6.703419,NaN,NaN,NaN,5.215099,NaN,NaN,NaN
21,NaN,서대문구,시군구,6.774028,4.958874,6.362067,5.307654,25,221.0,76,...,5.867918,7.691735,6.712804,NaN,NaN,NaN,5.307654,NaN,NaN,NaN
22,NaN,마포구,시군구,6.218859,5.029852,6.330136,5.190384,81,216.0,81,...,6.012158,7.421096,6.830116,NaN,NaN,NaN,5.235667,NaN,NaN,5.145100
23,NaN,양천구,시군구,6.797443,5.486214,6.181157,5.143113,22,180.0,99,...,5.722381,6.226963,7.114011,NaN,NaN,NaN,5.143113,NaN,NaN,NaN
24,NaN,강서구,시군구,6.122810,5.403314,6.134554,5.122545,89,186.0,104,...,6.066261,6.051285,6.637724,NaN,NaN,NaN,5.122545,NaN,NaN,NaN
25,NaN,구로구,시군구,6.466804,5.658555,5.997623,5.256235,47,165.0,123,...,5.916348,6.621050,6.560299,NaN,NaN,NaN,5.256235,NaN,NaN,NaN
26,NaN,금천구,시군구,5.717931,5.747715,5.765527,5.184248,156,156.0,150,...,5.830530,5.671441,6.161438,NaN,NaN,NaN,5.184248,NaN,NaN,NaN
27,NaN,영등포구,시군구,5.736966,5.276714,5.947886,5.184248,151,200.0,131,...,5.717729,5.863737,6.548568,NaN,NaN,NaN,5.184248,NaN,NaN,NaN
28,NaN,동작구,시군구,6.413947,5.150327,6.383860,5.081409,54,210.0,70,...,5.870536,7.703606,6.820731,NaN,NaN,NaN,5.081409,NaN,NaN,NaN
29,NaN,관악구,시군구,6.303283,5.187649,5.965550,5.101977,70,208.0,127,...,5.940750,5.858989,6.370254,NaN,NaN,NaN,5.101977,NaN,NaN,NaN
30,NaN,서초구,시군구,6.912580,4.749177,6.056643,5.970798,16,226.0,115,...,7.093372,5.692807,7.404944,NaN,NaN,NaN,5.328221,NaN,NaN,6.613376
31,NaN,강남구,시군구,6.469327,4.643982,6.052699,5.989373,45,228.0,116,...,5.945247,6.198474,7.536333,NaN,NaN,NaN,5.369357,NaN,NaN,6.609388
32,NaN,송파구,시군구,6.599652,5.001014,5.931980,5.324271,37,220.0,133,...,5.865246,6.110635,6.874694,NaN,NaN,NaN,5.194532,NaN,NaN,5.454011
33,NaN,강동구,시군구,6.588095,5.111546,6.118930,5.163680,38,213.0,107,...,6.287758,6.098765,6.759729,NaN,NaN,NaN,5.163680,NaN,NaN,NaN
34,NaN,중구_부산,시군구,6.119775,5.325167,5.896751,6.593132,90,195.0,138,...,5.877146,5.393680,6.013626,NaN,NaN,NaN,6.593132,NaN,NaN,NaN
35,NaN,서구_부산,시군구,6.745793,4.896252,5.967967,5.617906,27,222.0,126,...,5.958831,5.645327,6.335060,NaN,NaN,NaN,5.544182,NaN,NaN,5.691629
36,NaN,동구_부산,시군구,5.718079,5.218016,6.344203,5.811562,155,205.0,79,...,5.849841,5.583602,6.337406,NaN,NaN,NaN,5.811562,NaN,NaN,NaN
37,NaN,영도구,시군구,5.608116,5.283981,6.010536,5.485712,177,198.0,120,...,5.800472,6.485731,5.877544,NaN,NaN,NaN,5.585317,NaN,NaN,5.386106
38,NaN,부산진구,시군구,5.869409,5.010539,6.789758,5.194532,131,218.0,13,...,5.823377,7.167076,6.485219,NaN,NaN,NaN,5.194532,NaN,NaN,NaN
39,NaN,동래구,시군구,6.518744,5.042850,6.417171,5.178942,41,214.0,60,...,5.726447,6.234085,7.081163,NaN,NaN,NaN,5.173964,NaN,NaN,5.183920
40,NaN,남구_부산,시군구,5.973834,5.207365,6.743483,5.305271,116,207.0,15,...,5.779535,8.081076,6.684649,NaN,NaN,NaN,5.328221,NaN,NaN,5.282321
41,NaN,북구_부산,시군구,6.051196,5.436975,6.563123,5.310928,102,184.0,39,...,5.882839,6.272069,6.473488,NaN,NaN,NaN,5.225383,NaN,NaN,5.396474
42,NaN,해운대구,시군구,6.165626,5.207785,6.309150,5.267101,85,206.0,85,...,5.876734,6.416884,6.898157,NaN,NaN,NaN,5.184248,NaN,NaN,5.349955
43,NaN,사하구,시군구,5.887318,5.486245,6.540991,5.352114,128,179.0,44,...,5.696193,7.347502,6.609570,NaN,NaN,NaN,5.101977,NaN,NaN,5.602250
44,NaN,금정구,시군구,6.784665,5.008876,6.824894,5.152401,23,219.0,10,...,5.821250,7.625263,6.661187,NaN,NaN,NaN,5.266519,NaN,NaN,5.038284
45,NaN,강서구,시군구,6.044403,5.882748,6.313632,5.167733,105,137.0,84,...,6.066261,6.312428,7.092895,NaN,NaN,NaN,5.194532,NaN,NaN,5.140935
46,NaN,연제구,시군구,6.055419,5.021688,6.167699,5.071126,101,217.0,102,...,5.840002,6.822843,6.947428,NaN,NaN,NaN,5.071126,NaN,NaN,NaN
47,NaN,수영구,시군구,6.417365,4.855602,6.576046,5.163680,53,223.0,35,...,6.457986,6.010926,6.628340,NaN,NaN,NaN,5.163680,NaN,NaN,NaN
48,NaN,사상구,시군구,6.273663,5.390951,7.193647,5.112261,73,189.0,3,...,5.992381,8.460919,6.292828,NaN,NaN,NaN,5.112261,NaN,NaN,NaN
49,NaN,기장군,시군구,6.301682,6.209961,6.384535,5.307839,71,81.0,69,...,5.860476,6.336168,6.977929,NaN,NaN,NaN,5.307654,NaN,NaN,5.308025
50,NaN,중구_대구,시군구,7.206598,5.034852,6.187782,5.945561,4,215.0,98,...,5.877146,5.828126,6.743305,NaN,NaN,NaN,6.068657,NaN,NaN,5.822465
51,NaN,동구_대구,시군구,6.229476,5.361152,6.425690,5.666673,80,192.0,58,...,5.849841,5.768776,6.478180,NaN,NaN,NaN,5.235667,NaN,NaN,6.097678
52,NaN,서구_대구,시군구,6.011164,5.463921,5.882173,6.743808,111,182.0,139,...,5.958831,5.391306,6.245903,NaN,NaN,NaN,5.348789,NaN,NaN,8.138826
53,NaN,남구_대구,시군구,5.759150,4.830797,6.445012,6.307917,148,225.0,55,...,5.779535,6.908308,6.663533,NaN,NaN,NaN,5.431060,NaN,NaN,7.184774
54,NaN,북구_대구,시군구,5.833298,5.346734,6.839742,5.528016,138,193.0,9,...,5.882839,7.193191,6.658841,NaN,NaN,NaN,5.225383,NaN,NaN,5.830649
55,NaN,수성구,시군구,7.028365,4.847253,6.566753,5.410478,10,224.0,37,...,6.041184,6.198474,7.114011,NaN,NaN,NaN,5.215099,NaN,NaN,5.605856
56,NaN,달서구,시군구,6.483191,5.218367,6.795098,5.753222,44,204.0,12,...,5.855083,6.742126,6.848886,NaN,NaN,NaN,5.163680,NaN,NaN,6.342764
57,NaN,달성군,시군구,6.100788,5.839932,6.533290,5.622355,94,142.0,45,...,5.861860,5.965820,6.705766,NaN,NaN,NaN,5.153397,NaN,NaN,6.091313
58,NaN,중구_인천,시군구,6.030274,5.618097,6.141389,5.749777,107,169.0,103,...,5.877146,5.809134,6.576722,NaN,NaN,NaN,6.243482,NaN,NaN,5.256073
59,NaN,동구_인천,시군구,5.325112,6.046412,6.741807,5.439864,202,104.0,17,...,5.849841,7.359372,6.152053,NaN,NaN,NaN,5.677872,NaN,NaN,5.201856

In [142]:
temp = pd.merge(body, id[['광역', '자치']], how = 'left', left_on = 'dist', right_on = '자치')

In [143]:
temp[10:20]

,Unnamed: 0,dist,type,보건_영역평균,복지_영역평균,교육_영역평균,문화_영역평균,순위:보건,순위:복지,순위:교육,...,교육4 표준화값,교육5 표준화값,문화1 표준화값,문화2 표준화값,문화3 표준화값,문화4 표준화값,문화5 표준화값,문화6 표준화값,광역,자치
10,NaN,서울_중구,시군구,6.897709,5.365084,6.409564,6.263367,17,191.0,62,...,6.206017,NaN,NaN,NaN,6.911931,NaN,NaN,5.614803,NaN,NaN
11,NaN,용산구,시군구,6.631592,5.127551,5.803642,5.786113,33,211.0,147,...,6.194286,NaN,NaN,NaN,5.688156,NaN,NaN,5.884070,서울,용산구
12,NaN,성동구,시군구,5.984506,5.271905,5.962873,5.359073,115,202.0,129,...,6.119206,NaN,NaN,NaN,5.359073,NaN,NaN,NaN,서울,성동구
13,NaN,광진구,시군구,6.325881,5.152073,6.584678,5.143113,67,209.0,32,...,6.959159,NaN,NaN,NaN,5.143113,NaN,NaN,NaN,서울,광진구
14,NaN,동대문구,시군구,6.608022,5.414188,6.649697,5.136839,35,185.0,26,...,6.621301,NaN,NaN,NaN,5.204816,NaN,NaN,5.068862,서울,동대문구
15,NaN,중랑구,시군구,5.644073,5.330522,5.987926,5.029991,169,194.0,124,...,6.313944,NaN,NaN,NaN,5.029991,NaN,NaN,NaN,서울,중랑구
16,NaN,성북구,시군구,5.632359,5.277801,6.686061,5.410492,171,199.0,21,...,6.736267,NaN,NaN,NaN,5.410492,NaN,NaN,NaN,서울,성북구
17,NaN,강북구,시군구,5.715546,5.237576,9.021673,5.266519,157,203.0,1,...,6.701073,NaN,NaN,NaN,5.266519,NaN,NaN,NaN,서울,강북구
18,NaN,도봉구,시군구,5.581343,5.702790,5.938474,5.215099,181,164.0,132,...,6.450026,NaN,NaN,NaN,5.215099,NaN,NaN,NaN,서울,도봉구
19,NaN,노원구,시군구,6.950992,5.855179,6.617947,5.963732,13,139.0,28,...,6.611916,NaN,NaN,NaN,5.245951,NaN,NaN,6.681514,서울,노원구

In [144]:
temp['Unnamed: 0'] = temp['광역']
temp.drop(['광역', '자치'], axis = 1, inplace = True)
temp[40:60]

,Unnamed: 0,dist,type,보건_영역평균,복지_영역평균,교육_영역평균,문화_영역평균,순위:보건,순위:복지,순위:교육,...,교육2 표준화값,교육3 표준화값,교육4 표준화값,교육5 표준화값,문화1 표준화값,문화2 표준화값,문화3 표준화값,문화4 표준화값,문화5 표준화값,문화6 표준화값
40,부산,동래구,시군구,6.518744,5.042850,6.417171,5.178942,41,214.0,60,...,5.726447,6.234085,7.081163,NaN,NaN,NaN,5.173964,NaN,NaN,5.183920
41,NaN,남구_부산,시군구,5.973834,5.207365,6.743483,5.305271,116,207.0,15,...,5.779535,8.081076,6.684649,NaN,NaN,NaN,5.328221,NaN,NaN,5.282321
42,NaN,북구_부산,시군구,6.051196,5.436975,6.563123,5.310928,102,184.0,39,...,5.882839,6.272069,6.473488,NaN,NaN,NaN,5.225383,NaN,NaN,5.396474
43,부산,해운대구,시군구,6.165626,5.207785,6.309150,5.267101,85,206.0,85,...,5.876734,6.416884,6.898157,NaN,NaN,NaN,5.184248,NaN,NaN,5.349955
44,부산,사하구,시군구,5.887318,5.486245,6.540991,5.352114,128,179.0,44,...,5.696193,7.347502,6.609570,NaN,NaN,NaN,5.101977,NaN,NaN,5.602250
45,부산,금정구,시군구,6.784665,5.008876,6.824894,5.152401,23,219.0,10,...,5.821250,7.625263,6.661187,NaN,NaN,NaN,5.266519,NaN,NaN,5.038284
46,서울,강서구,시군구,6.044403,5.882748,6.313632,5.167733,105,137.0,84,...,6.066261,6.312428,7.092895,NaN,NaN,NaN,5.194532,NaN,NaN,5.140935
47,부산,강서구,시군구,6.044403,5.882748,6.313632,5.167733,105,137.0,84,...,6.066261,6.312428,7.092895,NaN,NaN,NaN,5.194532,NaN,NaN,5.140935
48,부산,연제구,시군구,6.055419,5.021688,6.167699,5.071126,101,217.0,102,...,5.840002,6.822843,6.947428,NaN,NaN,NaN,5.071126,NaN,NaN,NaN
49,부산,수영구,시군구,6.417365,4.855602,6.576046,5.163680,53,223.0,35,...,6.457986,6.010926,6.628340,NaN,NaN,NaN,5.163680,NaN,NaN,NaN
50,부산,사상구,시군구,6.273663,5.390951,7.193647,5.112261,73,189.0,3,...,5.992381,8.460919,6.292828,NaN,NaN,NaN,5.112261,NaN,NaN,NaN
51,부산,기장군,시군구,6.301682,6.209961,6.384535,5.307839,71,81.0,69,...,5.860476,6.336168,6.977929,NaN,NaN,NaN,5.307654,NaN,NaN,5.308025
52,NaN,중구_대구,시군구,7.206598,5.034852,6.187782,5.945561,4,215.0,98,...,5.877146,5.828126,6.743305,NaN,NaN,NaN,6.068657,NaN,NaN,5.822465
53,NaN,동구_대구,시군구,6.229476,5.361152,6.425690,5.666673,80,192.0,58,...,5.849841,5.768776,6.478180,NaN,NaN,NaN,5.235667,NaN,NaN,6.097678
54,NaN,서구_대구,시군구,6.011164,5.463921,5.882173,6.743808,111,182.0,139,...,5.958831,5.391306,6.245903,NaN,NaN,NaN,5.348789,NaN,NaN,8.138826
55,NaN,남구_대구,시군구,5.759150,4.830797,6.445012,6.307917,148,225.0,55,...,5.779535,6.908308,6.663533,NaN,NaN,NaN,5.431060,NaN,NaN,7.184774
56,NaN,북구_대구,시군구,5.833298,5.346734,6.839742,5.528016,138,193.0,9,...,5.882839,7.193191,6.658841,NaN,NaN,NaN,5.225383,NaN,NaN,5.830649
57,대구,수성구,시군구,7.028365,4.847253,6.566753,5.410478,10,224.0,37,...,6.041184,6.198474,7.114011,NaN,NaN,NaN,5.215099,NaN,NaN,5.605856
58,대구,달서구,시군구,6.483191,5.218367,6.795098,5.753222,44,204.0,12,...,5.855083,6.742126,6.848886,NaN,NaN,NaN,5.163680,NaN,NaN,6.342764
59,대구,달성군,시군구,6.100788,5.839932,6.533290,5.622355,94,142.0,45,...,5.861860,5.965820,6.705766,NaN,NaN,NaN,5.153397,NaN,NaN,6.091313

In [145]:
temp.to_excel("/home/mglee/VSCODE/git/ISDS/region/merge0118.xlsx")

In [146]:
j_rank = temp[temp['dist'] == '제주시'][['순위:보건', '순위:복지', '순위:교육', '순위:문화']]
s_rank = temp[temp['dist'] == '서귀포시'][['순위:보건', '순위:복지', '순위:교육', '순위:문화']]

In [147]:
j_rank['순위:보건'].item()

170

In [156]:
check_lst = ['순위:보건', '순위:복지', '순위:교육', '순위:문화']

global_lst = []

for col in check_lst:
    lst = []
    for item_rank in temp[col]:
        modi = 0
        if item_rank > j_rank[col].item():
            modi += 1
        if item_rank > s_rank[col].item():
            modi += 1
        lst.append(item_rank - modi)
    global_lst.append(lst)

In [158]:
new_rank = pd.DataFrame(global_lst).T

new_df = pd.concat([temp, new_rank], axis = 1)
new_df.to_excel("/home/mglee/VSCODE/git/ISDS/region/temp.xlsx")

In [168]:
new_df[new_df['dist'].duplicated()]

,Unnamed: 0,dist,type,보건_영역평균,복지_영역평균,교육_영역평균,문화_영역평균,순위:보건,순위:복지,순위:교육,...,문화1 표준화값,문화2 표준화값,문화3 표준화값,문화4 표준화값,문화5 표준화값,문화6 표준화값,0,1,2,3
25,부산,강서구,시군구,6.122810,5.403314,6.134554,5.122545,89,186.0,104,...,NaN,NaN,5.122545,NaN,NaN,NaN,89.0,184.0,103.0,220.0
46,서울,강서구,시군구,6.044403,5.882748,6.313632,5.167733,105,137.0,84,...,NaN,NaN,5.194532,NaN,NaN,5.140935,105.0,137.0,84.0,209.0
47,부산,강서구,시군구,6.044403,5.882748,6.313632,5.167733,105,137.0,84,...,NaN,NaN,5.194532,NaN,NaN,5.140935,105.0,137.0,84.0,209.0
133,경남,고성군,시군구,5.719011,5.829421,5.120252,7.985548,154,143.5,203,...,NaN,NaN,9.781119,NaN,NaN,6.189976,154.0,143.5,201.0,3.0
231,강원,고성군,시군구,6.353020,5.829421,5.361112,6.244762,60,143.5,185,...,NaN,NaN,6.839944,NaN,NaN,5.649580,60.0,143.5,183.0,60.0
232,경남,고성군,시군구,6.353020,5.829421,5.361112,6.244762,60,143.5,185,...,NaN,NaN,6.839944,NaN,NaN,5.649580,60.0,143.5,183.0,60.0